package br.com.guardiaosistemas.tca.execucao.frames.helper;

import java.util.ArrayList;
import java.util.List;

import br.com.guardiaosistemas.tca.execucao.consts.C;
import br.com.guardiaosistemas.tca.execucao.model.entity.HitEntity;

public class DataTestHelper {
	
	public static List<HitEntity> getTrainingList1() {
		List<HitEntity> hitTrn1 = new ArrayList<>();
		hitTrn1.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		hitTrn1.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		hitTrn1.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		hitTrn1.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		hitTrn1.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		hitTrn1.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		return hitTrn1;
	}
	
	public static List<HitEntity> getTrainingList2() {
		List<HitEntity> hitTrn2 = new ArrayList<>();
		hitTrn2.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		hitTrn2.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		hitTrn2.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		return hitTrn2;
	}

	public static List<HitEntity> getTrainingList1_30() {
		List<HitEntity> hitTrn1_30 = new ArrayList<>();
		hitTrn1_30.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		hitTrn1_30.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		hitTrn1_30.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		hitTrn1_30.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		hitTrn1_30.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		hitTrn1_30.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		hitTrn1_30.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		hitTrn1_30.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		return hitTrn1_30;
	}
	
	private static List<HitEntity> getTestList1M30S() {
		List<HitEntity> test1M30S = new ArrayList<>();
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test1M30S.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		
		return test1M30S;
	}
	
	private static List<HitEntity> getTestList5M() {
		List<HitEntity> test5M = new ArrayList<>();
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test5M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));

		return test5M;
	}
	
	private static List<HitEntity> getTestList10M() {
		List<HitEntity> test10M = new ArrayList<>(getTestList5M());
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test10M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		
		return test10M;
	}
	
	private static List<HitEntity> getTestList15M() {
		List<HitEntity> test15M = new ArrayList<>(getTestList10M());
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_LOW, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 2));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 1));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_BALLON, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		test15M.add(new HitEntity(C.T_STAR, C.F_HIGH, 4));
		
		return test15M;
	}
	
	public static List<HitEntity> getTestList(int time) {
		if (time == 1) {
			return getTestList1M30S();
		} else if (time == 5) {
			return getTestList5M();
		} else if (time == 10) {
			return getTestList10M();
		} else {
			return getTestList15M();
		}
	}
	
	public static List<HitEntity> getExample() {
		List<HitEntity> list = new ArrayList<>();
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 342, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 368, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 332, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 404, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 364, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 388, true));
		list.add(new HitEntity(C.T_STAR, 500, true));
		list.add(new HitEntity(C.T_BALLON, 252, true));
		list.add(new HitEntity(C.T_STAR, 484, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 344, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 384, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 392, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 399, true));
		list.add(new HitEntity(C.T_STAR, 356, true));
		list.add(new HitEntity(C.T_STAR, 392, true));
		list.add(new HitEntity(C.T_STAR, 328, true));
		list.add(new HitEntity(C.T_STAR, 304, true));
		list.add(new HitEntity(C.T_STAR, 316, true));
		list.add(new HitEntity(C.T_STAR, 412, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 420, true));
		list.add(new HitEntity(C.T_STAR, 440, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 400, true));
		list.add(new HitEntity(C.T_STAR, 448, true));
		list.add(new HitEntity(C.T_STAR, 504, true));
		list.add(new HitEntity(C.T_STAR, 368, true));
		list.add(new HitEntity(C.T_STAR, 408, true));
		list.add(new HitEntity(C.T_STAR, 340, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 396, true));
		list.add(new HitEntity(C.T_STAR, 328, true));
		list.add(new HitEntity(C.T_STAR, 320, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 435, true));
		list.add(new HitEntity(C.T_STAR, 488, true));
		list.add(new HitEntity(C.T_STAR, 308, true));
		list.add(new HitEntity(C.T_STAR, 359, true));
		list.add(new HitEntity(C.T_STAR, 400, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 384, true));
		list.add(new HitEntity(C.T_STAR, 407, true));
		list.add(new HitEntity(C.T_STAR, 396, true));
		list.add(new HitEntity(C.T_STAR, 352, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 367, true));
		list.add(new HitEntity(C.T_STAR, 520, true));
		list.add(new HitEntity(C.T_STAR, 348, true));
		list.add(new HitEntity(C.T_STAR, 448, true));
		list.add(new HitEntity(C.T_STAR, 348, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 336, true));
		list.add(new HitEntity(C.T_STAR, 560, true));
		list.add(new HitEntity(C.T_STAR, 492, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 396, true));
		list.add(new HitEntity(C.T_STAR, 416, true));
		list.add(new HitEntity(C.T_STAR, 392, true));
		list.add(new HitEntity(C.T_STAR, 328, true));
		list.add(new HitEntity(C.T_STAR, 324, true));
		list.add(new HitEntity(C.T_STAR, 392, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_STAR, 464, true));
		list.add(new HitEntity(C.T_STAR, 420, true));
		list.add(new HitEntity(C.T_STAR, 420, true));
		list.add(new HitEntity(C.T_STAR, 436, true));
		list.add(new HitEntity(C.T_STAR, 400, true));
		list.add(new HitEntity(C.T_STAR, 324, true));
		list.add(new HitEntity(C.T_BALLON, 0, false));
		list.add(new HitEntity(C.T_BALLON, 332, true));
		list.add(new HitEntity(C.T_STAR, 440, true));
		list.add(new HitEntity(C.T_STAR, 428, true));
//		list.add(new HitEntity(C.T_STAR, 0, false));

		return list;
	}
}
